
Traceback (most recent call last):
  File "/Volumes/work/zupermind/env/pysnip/src/pysnip/make/job.py", line 84, in run
    eval(pycode_compiled)
  File "snippets/80_exercise/80_exercise-cat1.py", line 1, in <module>
    from act4e_tex import visualize_data_file;visualize_data_file('cat1');
  File "/Volumes/work/ETH/2012-DPCAT/ACT4E-private/src/act4e_tex/visualize.py", line 16, in visualize_data_file
    s = alldata[bn]
KeyError: 'cat1'
