
Traceback (most recent call last):
  File "/Volumes/work/zupermind/env/pysnip/src/pysnip/make/job.py", line 79, in run
    eval(pycode_compiled)
  File "snippets/50_functor_code/50_functor_code-fun1.py", line 1, in <module>
    from act4e_tex import visualize_data_file;visualize_data_file('fun1');
  File "/Volumes/work/zupermind/ACT4E-z7-stage/ACT4E-private/src/act4e_tex/visualize.py", line 24, in visualize_data_file
    s = alldata[bn]
KeyError: 'fun1'
