
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pysnip/make/job.py", line 79, in run
    eval(pycode_compiled)
  File "snippets/25_tradeoffs_exercises/25_tradeoffs_exercises-poset1.py", line 1, in <module>
    from act4e_tex import visualize_data_file;visualize_data_file('poset1');
  File "/Users/gioele/Desktop/act4e/book/ACT4E/ACT4E-private/src/act4e_tex/visualize.py", line 21, in visualize_data_file
    s = alldata[bn]
KeyError: 'poset1'
